<script setup lang="ts">
import { usePresentation } from '../../stores/presentation';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import ProgressBar from 'primevue/progressbar';
import Slider from 'primevue/slider';
import StackedLayout from '../../layouts/StackedLayout.vue';
import Checkbox from 'primevue/checkbox';
import { computed, ref, watch } from 'vue';
import { useBusy } from '../../composables/useBusy';
import { useRouter } from 'vue-router';
import { useSlideBuilder } from '../../composables/useSlideBuilder';
import { RouteNames } from '../../routes';
import type { Slide } from '../../types/slide-schema';
import FolderPicker from '../FolderPicker/FolderPicker.vue';
import { loadBackupImages, pickRandomNumbers } from './Wizard.util';

const presentation = usePresentation();
const { push } = useRouter();
const { findTopic, generateImage, generateText } = useSlideBuilder();
const { op, isBusy } = useBusy();
const length = ref<number>(5);
const images = ref<number>(3);
const duration = ref<number>(15);
const addText = ref<boolean>(true);
const localImagePath = ref<string>('');
const tasksDone = ref<number>(0);
const tasksTotal = ref<number>(0);

const progress = computed<number>(() => {
  if (tasksTotal.value <= 0) return 0;
  const percentage = tasksDone.value / tasksTotal.value;
  return Math.round(percentage * 100);
});
const topicIsUserProvided = computed<boolean>(() => !!presentation.topic);
const imagesAreUserProvided = computed<boolean>(() => images.value > 0);

watch(duration, (value: number) => {
  presentation.timer = {
    timePerTick: value * 1000,
  };
});

interface GenerationOptions {
  topic: string;
  slideNo: number;
  withImage: boolean;
  withText: boolean;
}

async function generateSlide({ topic, slideNo, withImage, withText }: GenerationOptions): Promise<Slide> {
  const slide: Slide = {};
  if (withText) {
    const text = await generateText(topic, slideNo);
    slide.text = { text };
    console.debug(`Generated slide's ${slideNo} text: "${text}"`);
  }
  if (!withImage) return slide;

  try {
    const image = await generateImage(slide.text?.text);
    slide.image = { base64: image };
    console.debug(`Generated slide's ${slideNo} image`);
  } catch (e) {
    console.error(e);
  }

  return slide;
}

const generate = () => {
  tasksDone.value = 0;
  tasksTotal.value = 0;

  const slidesWithAiImage = new Set<number>(Array.from(pickRandomNumbers(images.value, length.value)));

  op(async () => {
    const backupImages = localImagePath.value
      ? await loadBackupImages(localImagePath.value, length.value - images.value)
      : [];

    if (!presentation.topic) {
      presentation.topic = await findTopic();
    }
    console.debug('Generating slides');

    const promises: Promise<Slide>[] = [];
    for (let i = 0; i < length.value; i++) {
      const withAiImage = slidesWithAiImage.has(i);
      const slideGeneration = generateSlide({
        topic: presentation.topic,
        slideNo: i + 1,
        withText: addText.value,
        withImage: withAiImage,
      }).then((slide) => {
        tasksDone.value++;

        if (!withAiImage && backupImages.length) {
          const [localImage] = backupImages.splice(0, 1);
          slide.image = { base64: localImage };
        }

        return slide;
      });
      promises.push(slideGeneration);
    }
    tasksTotal.value = promises.length;
    presentation.slides = await Promise.all(promises);
    console.debug('Done generating');
    void push({ name: RouteNames.Editor });
  });
};
</script>

<template>
  <main class="split">
    <div class="robot" />

    <main>
      <StackedLayout>
        <h2>Wizard</h2>

        <h3>Topic</h3>

        <p>
          Hi! I'm a wizard. I do presentations and stuff. What is the <strong>topic</strong> of your presentation? Feel
          free to leave it blank, then I'll just come up with something for you.
        </p>

        <InputText data-testid="topic-input" v-model.trim="presentation.topic" placeholder="Topic" />

        <p v-if="topicIsUserProvided">A topic has been provided. GPT will not be tasked.</p>
        <p v-else>A topic has not been provided. GPT will find you one.</p>

        <h3>Images</h3>

        <div class="checkbox">
          <Checkbox v-model="addText" binary input-id="add-text-checkbox" />
          <label for="add-text-checkbox">Generate texts</label>
        </div>

        <p v-if="addText">Slide texts will be generated by GPT.</p>
        <p v-else>Slides will contain no text.</p>

        <h3>Length</h3>

        <p>How long you want it to be?</p>

        <div class="slider">
          <span class="number">{{ length }}</span>
          <Slider data-testid="slides-length-input" v-model.number="length" :min="3" :max="30" :step="1" />
        </div>

        <p>How many seconds between slides (in seconds)?</p>
        <div class="slider">
          <span class="number">{{ length }}</span>
          <Slider data-testid="duration-input" v-model.number="duration" :min="5" :max="60" :step="1" />
        </div>

        <h3>Images</h3>

        <p>How many images should the AI generate?</p>

        <div class="slider">
          <span class="number">{{ images }}</span>
          <Slider data-testid="image-number-input" v-model.number="images" :min="0" :max="5" :step="1" />
        </div>

        <p v-if="imagesAreUserProvided">No AI images will be generated.</p>
        <p v-else>DALL-E will provide some AI-generated images.</p>

        <p>Do you want me to use a folder of other images for the rest?</p>

        <div>
          <FolderPicker @update:folder="(folder: string) => (localImagePath = folder)" />
        </div>

        <ProgressBar
          data-testid="generate-progress-bar"
          v-if="isBusy"
          :mode="progress ? 'determinate' : 'indeterminate'"
          :value="progress"
        />

        <Button
          data-testid="generate-button"
          :disabled="isBusy"
          :loading="isBusy"
          label="Generate"
          icon="pi pi-search"
          @click="generate"
        />
      </StackedLayout>
    </main>
  </main>
</template>

<style scoped>
.split {
  display: grid;
  width: 100%;
  height: 100%;
  gap: 8px;
  grid-template-columns: minmax(64px, 25%) 1fr;
  align-items: stretch;
}

div.robot {
  background-image: url('/speaking_robot.jpg');
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

div.slider {
  display: grid;
  align-items: center;
  grid-template-columns: minmax(32px, 10%) 1fr;
  gap: 8px;
}

div.checkbox {
  display: flex;
  flex-direction: row;
  gap: 8px;
}

.number {
  text-align: right;
}
</style>
