name: 'CI Main'

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run vitest
        run: npm run test:coverage
