name: 'CI PR'

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run vitest
        run: npm run test:coverage

      - name: Report Coverage
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@123077f0e59cbc2e9afd2c454dbc14ae36737874 # v2

      - name: Upload Coverage
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: coverage
          path: coverage/
          retention-days: 5
